runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  URL: https://inquirer.inquiry.institute
  NODE_ENV: production

# For Cloud SQL connection
beta_settings:
  cloud_sql_instances: PROJECT_ID:REGION:INSTANCE_NAME
